on:
  push: # Runs whenever a commit is pushed to the repository...
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions: 
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
        JVM_OPTS: -Xmx3200m
        JDK_JAVA_OPTIONS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED
    steps: 
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        - uses: wagoid/commitlint-github-action@5ce82f5d814d4010519d15f0552aec4f17a1e1fe # v5
        - name: Setup Java
          uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4
          with:
            distribution: 'temurin'
            java-version: 17
        - name: Setup submodule
          run: git submodule update --init --recursive
        - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
          with:
            cache: "npm"
            node-version-file: ".nvmrc"
        - name: Info
          run: |
            cat <<EOF
            Node version: $(node --version)
            NPM version: $(npm --version)
            GitHub ref: ${{ github.ref }}
            GitHub head ref: ${{ github.head_ref }}
            EOF
        - name: Setup
          run: |
            sudo apt update
            sudo apt install pkg-config libcairo2-dev libpango1.0-dev libssl-dev libjpeg62-dev libgif-dev
            TRAVIS_BRANCH="${{github.ref_name}}" travis/setup-git.sh # Configure git user info
            travis/install-assets.sh
            npm set progress=false
            which gulp || npm install -g gulp-cli    
        - name: Install NPM Dependencies
          run: npm ci
        - run: gulp jshint
        - run: gulp minify
        - run: gulp test
        - run: gulp zip
        - name: Tag build
          if: (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/hotfix') || startsWith(github.ref, 'refs/heads/release')
          run: |
            TRAVIS_TAG="${{github.ref_name}}" TRAVIS_COMMIT="${{github.sha}}" travis/deploy-prebuilt.sh
        
